### ISSUE TITLE
Make bucket_name configurable

### ISSUE THREAD

**Issue by mmkay** [canonical/loki-coordinator-k8s-operator#4]
### Enhancement Proposal

Our current coordinator charm assumes a pre-defined name of the loki s3 bucket:

https://github.com/canonical/loki-coordinator-k8s-operator/blob/main/src/charm.py#L66

We should make it configurable, with a reasonable default (probably the current value).

**Comment by lucabello** [comment]
This is now possible via cos-lib :)
